# Site settings
#
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "/jekyll" # the subpath of your site, e.g. /blog
# url: "/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# 

title: Carnet de notes de YerebY
email: yereby@gmail.com

# Build settings

markdown: kramdown
exclude: ["README.md"]

# Settings

timezone: Europe/Paris

sass:
  sass_dir: css/_sass

url: "/"
